apiVersion: v1
kind: Service
metadata:
  name: request-service
  labels:
    app: request-service
    service: request-service
    version: v1
  namespace: apps
spec:
  ports:
  - port: 8080
    name: http
  type: ClusterIP
  selector:
    app: request-service